# Generated by Django 4.2 on 2024-12-25 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('apk_file', models.FileField(blank=True, null=True, upload_to='apk_files')),
                ('download_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.TextField(choices=[('General Population', 'General Population'), ('Client Group', 'Client Group')], max_length=200)),
                ('client_group', models.TextField(blank=True, choices=[('FSW', 'FSW'), ('MSM', 'MSM'), ('PWID,', 'PWID,'), ('MAT,', 'MAT,'), ('AGYW,', 'AGYW,')], max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('pin_type', models.CharField(blank=True, choices=[('PERMANENT', 'PERMANENT')], max_length=50, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('hotspot', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District Supporting Ward')),
                ('ward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supporting Ward')),
                ('hfrcode', models.CharField(blank=True, max_length=15, null=True, verbose_name='HFR Code')),
                ('supporting_facility', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supporting Facility')),
                ('responsible_cso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsible CSO')),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsible Person')),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number')),
                ('app_password', models.CharField(blank=True, max_length=15, null=True, verbose_name='App Password')),
                ('pin_range_start', models.PositiveIntegerField()),
                ('pin_range_end', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'District Support',
                'verbose_name_plural': 'District Supports',
                'ordering': ['district', 'ward'],
            },
        ),
        migrations.CreateModel(
            name='KvpGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('pin_code_start', models.PositiveIntegerField()),
                ('pin_code_end', models.PositiveIntegerField()),
                ('age_start', models.PositiveIntegerField()),
                ('age_end', models.PositiveIntegerField()),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('machine_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slot_number', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='slots/')),
                ('product_type', models.CharField(choices=[('Condoms', 'Condoms'), ('Kits', 'Kits')], max_length=50)),
                ('product_subtype', models.CharField(blank=True, choices=[('Male Condoms', 'Male Condoms'), ('Female Condoms', 'Female Condoms'), ('Blood Kits', 'Blood Kits'), ('Oral Kits', 'Oral Kits')], max_length=50, null=True)),
                ('capacity', models.IntegerField()),
                ('quantity_available', models.IntegerField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('dispensed_amount', models.IntegerField(default=0)),
                ('dispensed_successful_amount', models.IntegerField(default=0)),
                ('product_type', models.CharField(blank=True, choices=[('Condoms', 'Condoms'), ('Kits', 'Kits')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.customer')),
                ('kvp_pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.facility')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.machine')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.slot')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, choices=[('Condoms', 'Condoms'), ('Kits', 'Kits')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50, null=True)),
                ('status_description', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback_status', models.CharField(blank=True, max_length=20, null=True)),
                ('trade_number', models.CharField(blank=True, max_length=200, null=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.machine')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.slot')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='MachineLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True)),
                ('function_code', models.CharField(blank=True, max_length=23, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.machine')),
            ],
        ),
        migrations.CreateModel(
            name='KvpPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=7, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.facility')),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.machine'),
        ),
        migrations.AddField(
            model_name='facility',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='registered_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.machine'),
        ),
    ]
