# Generated by Django 4.2 on 2024-12-02 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_registered_mashine_customer_registered_machine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slot_number', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='slots/')),
                ('product_type', models.CharField(choices=[('Condoms', 'Condoms'), ('Kits', 'Kits')], max_length=50)),
                ('capacity', models.IntegerField()),
                ('quantity_available', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.machine')),
            ],
        ),
    ]
