# Generated by Django 4.2 on 2024-12-05 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.slot'),
        ),
    ]
