# Generated by Django 4.2 on 2024-12-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_customer_description_customer_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
