# Generated by Django 4.2 on 2024-12-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='app_password',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='App Password'),
        ),
    ]
