# Generated by Django 4.2 on 2024-12-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_facility_app_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
