# Generated by Django 4.2 on 2024-12-12 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_machine_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dispensed_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dispensed_successful_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Condoms', 'Condoms'), ('Kits', 'Kits')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, choices=[('Condoms', 'Condoms'), ('Kits', 'Kits')], default='Pending', max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=50, null=True)),
                ('status_description', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback_status', models.CharField(blank=True, max_length=20, null=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.machine')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.slot')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.transaction')),
            ],
        ),
    ]
