# Generated by Django 4.2 on 2024-12-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_transactionlog_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='trade_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
