# Generated by Django 4.2 on 2024-12-12 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_machinelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelogs',
            name='function_code',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='machinelogs',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.machine'),
        ),
    ]
