# Generated by Django 4.2 on 2024-12-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_machinelogs_function_code_alter_machinelogs_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Condoms', 'Condoms'), ('Kits', 'Kits')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50, null=True),
        ),
    ]
