# Generated by Django 4.2 on 2024-12-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_transaction_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
