# Generated by Django 4.2 on 2024-12-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_machine_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
