# Generated by Django 4.2 on 2024-12-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_slot_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
