# Generated by Django 4.2 on 2024-12-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_slot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='product_subtype',
            field=models.CharField(blank=True, choices=[('Male Condoms', 'Male Condoms'), ('Female Condoms', 'Female Condoms'), ('Blood Kits', 'Blood Kits'), ('Oral Kits', 'Oral Kits')], max_length=50, null=True),
        ),
    ]
