# Generated by Django 4.2 on 2024-12-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_slot_product_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('apk_file', models.FileField(blank=True, null=True, upload_to='apk_files')),
                ('download_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
